name: localyft
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^8.0.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.5
  firebase_analytics: ^10.9.0
  firebase_app_check: ^0.2.1+19
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.20
  firebase_dynamic_links: ^5.4.19
  firebase_performance: ^0.9.3+19
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geocode: ^1.0.3
  geocoding: ^3.0.0
  geoflutterfire2: ^2.3.15
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  injectable: ^2.4.1
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  rounded_loading_button_plus: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.0.0
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    # - assets/icons/
    - assets/images/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial_regular.ttf
        - asset: assets/fonts/arial_bold.ttf
          weight: 100

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_medium.ttf
        - asset: assets/fonts/avenir_heavy.ttf
          weight: 300
